### PR TITLE
Dummy App

### PR DESCRIPTION
**Pull request by gr2m**
# WORK IN PROGRESS

in preparation for #5

### CODE REVIEW

**Comment by gr2m** [comment]
So it seems to work in general, but no CSS gets loaded, any idea why @courajs

**Comment by gr2m** [comment]
I’m trying to setup acceptance test, but looks like it cannot connect to Hoodie. Might it be something with the ports? I actually don’t even understand why `ember server` is starting the Hoodie server? wouldn’t we need to add the logic to `server/index.js`? Or is `ember server` requiring the `index.js` file and running the `serverMiddleware`?

**Comment by courajs** [comment]
I think `server/index

**Comment by courajs** [comment]
I think `server/index` and `serverMiddleware` are meant mainly for development, not test. Usually ajax calls are mocked out in test with [pretender](https://github.com/pretenderjs/pretender) or similar. I haven't looked into how we would get the server running in test yet

**Comment by courajs** [comment]
No reason off the top of my head the css wouldn't load, I'd have to dig into it.

**Comment by courajs** [comment]
Closing in favor of #16

**Pull request closed without merging**
