### PR TITLE
Fix (bug): Use '_id' instead of 'id' to unload (remotely removed) records from ember store

### PR DESCRIPTION
**Pull request by arunprasadr-zz**
Use '_id' instead of 'id' to peek record from ember data store

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
cheers!

**Comment by arunprasadr-zz** [comment]
Can you please tag and release a new version to the npm repositiory?

**Comment by gr2m** [comment]
my fault, I didn't follow our own commit conventions :) I created another empty commit that should fix it: https://github.com/hoodiehq/ember-hoodie/commit/326de4968b12db37fe37435455b31a36fe5c1020. Once the tests are passing it should release a new version

**Comment by gr2m** [comment]
https://github.com/hoodiehq/ember-hoodie/releases/tag/v2.3.5

**Pull request merged**
