### PR TITLE
completing some required configurations in readme example

### PR DESCRIPTION
**Pull request by brunopedroso**

### CODE REVIEW

**Comment by gr2m** [comment]
That should not be necessary, I’ll have a look into it, might be a bug with `hoodie` itself.

**Comment by brunopedroso** [comment]
The error occurs on this line if you don't set anyone of them:

https://github.com/hoodiehq/hoodie/blob/master/server/index.js#L27
TypeError: Cannot read property 'data' of undefined

maybe the `paths` config may be missing some initialization...

(btw, feel totally free to close my pull requests...)

**Comment by gr2m** [comment]
Thanks, I’ll try to reproduce the issue today

**Comment by gr2m** [comment]
Confirmed, but that is  an error in `hoodie`, it should set default values for `options.paths`. I’m looking into it. Thanks!

**Comment by gr2m** [comment]
The issue with `options.paths` will be resolved via https://github.com/hoodiehq/hoodie/pull/556. If you could review it, that’d be great :)

**Comment by brunopedroso** [comment]
great. Closing this one...

**Pull request closed without merging**
